services:
    db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_PASSWORD=postgres
      container_name: postgres
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - 5432:5432

    pgadmin:
      image: dpage/pgadmin4
      restart: always
      container_name: nest-pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=pgadmin4
      ports:
        - '5050:80'
      depends_on:
        - db

    server-service:
      build: 'server'
      volumes:
        - ./server:/home/node/app
        - ./server:/home/node/app/node_modules
      ports:
        - 3000:4000
      depends_on:
        - db

    client-service:
      build: 'client'
      volumes:
        - ./client:/home/node/app
      ports:
        - 8001:80
      depends_on:
        - server-service
